[DEFAULT]

# Server configuration
# host: The IP address the server will bind to (default: localhost)
# port: The port number the server will listen on (default: 5000)
host = localhost
port = 5000

# Authentication settings
# username: The username required for authentication (leave blank to disable authentication)
# password: The password required for authentication (leave blank to disable authentication)
username = 
password = 

# Workspace settings
# workspaces_config_path: The file to save the workspaces info. (default: workspaces.json)
workspaces_config_path = ./workspaces.json

# Default values for workspace settings
# working_dir: The directory to place .tex and work on. (default: ./workspace-default)
# tex_filename: The filename of the main .tex file. (default: main.tex)
# compile_cmd: The command line to compile latex. 
# (default: xelatex -interaction=nonstopmode -halt-on-error {{ TEX_FILENAME }})
working_dir = ./workspace-default
tex_filename = main.tex
compile_cmd = xelatex -interaction=nonstopmode -halt-on-error main.tex
