[DEFAULT]

# Server configuration
# HOST: The IP address the server will bind to (default: localhost)
# PORT: The port number the server will listen on (default: 5000)
HOST=
PORT=

# Authentication settings
# USERNAME: The username required for authentication (leave blank to disable authentication)
# PASSWORD: The password required for authentication (leave blank to disable authentication)
USERNAME=
PASSWORD=

# Workspace settings
# WORKSPACES_CONFIG_PATH: The file to save the workspaces info. (default: workspaces.json)
WORKSPACES_CONFIG_PATH=

# Default values for workspace settings
# WORKING_DIR: The directory to place .tex and work on. (default: ./workspace-default)
# TEX_FILENAME: The filename of the main .tex file. (default: main.tex)
# COMPILE_CMD: The command line to compile latex. 
# (default: xelatex -interaction=nonstopmode -halt-on-error {{ TEX_FILENAME }})
WORKING_DIR=
TEX_FILENAME=
COMPILE_CMD=


